entrada = input().split()
cod1 = int(entrada[0])
num1 = int(entrada[1])
val1 = float(entrada[2])
entrada2 = input().split()
cod2 = int(entrada2[0])
num2 = int(entrada2[1])
val2 = float(entrada2[2])
print('VALOR A PAGAR: R$ {:.2f}'.format((val1 * num1)+(val2 * num2)))
